language: java
jdk:
- oraclejdk8
- oraclejdk7

addons:
  apt_packages:
  - rpm

env:
- VERSION=1.0

script: "./gradlew clean shadowJar"

after_success:
- gem install fpm
- mkdir -p opt/opennms-sendevent-webhook etc/init.d etc/sysconfig
- cp init.d/opennms-sendevent-webhook etc/init.d
- cp build/libs/opennms-sendevent-webhook-0.1-all.jar opt/opennms-sendevent-webhook/
- touch etc/sysconfig/opennms-sendevent-webhook
- printf "#!/bin/sh\n/sbin/chkconfig --add opennms-sendevent-webhook\n" > after-install.sh
- printf "#!/bin/sh\n/sbin/chkconfig --remove opennms-sendevent-webhook\n" > before-remove.sh
- chmod +x after-install.sh before-remove.sh
- fpm -s dir -t rpm -a all -n opennms-sendevent-webhook -v ${VERSION} --iteration
  ${TRAVIS_JOB_ID} --description "OpenNMS send-event Web Hook" --after-install after-install.sh
  --before-remove before-remove.sh --config-files etc/sysconfig/opennms-sendevent-webhook
  --maintainer umberto.nicoletti@gmail.com --url https://github.com/unicolet/opennms-sendevent-webhook
  --rpm-user root --rpm-group root --directories opt/opennms-sendevent-webhook opt etc
- mkdir rpm
- mv *.rpm rpm
- ls -la rpm

deploy:
  provider: packagecloud
  username: unicoletti
  token:
    secure: Fzi+fEjpR7xhBcyEyHKwOzbO1KfqTFEz8nRoLezsBxSm6R5ks5LkdiqsonTjIr8iwLFXO4pvORphuqyoZl0qQWtj8WFIrM0Z5tqHrpSoquEcbtDxVkWRIJDVc/a5Xrxo15b36uMmo0nuujzZcYEP5Q3LyxFJV4MArlnIXSgsRps=
  repository: opennms
  local-dir: rpm
  dist: 'el/6'
  skip_cleanup: true
  on:
    branch: release-rpm
    jdk: oraclejdk7
